import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import LenisProvider from "@/components/LenisProvider";
import MouseFollowLight from "@/components/MouseFollow/MouseFollowLight";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // Choose the weights you need
  variable: "--font-poppins", // Optional: for CSS variable usage
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        
        
        <LenisProvider>
          <NavBar />
          <MouseFollowLight />
          {children}
        </LenisProvider>
        </body>
    </html>
  );
}
